Quick_Tab/urls.py
from django.contrib import admin
from django.urls import path
from Invoice import views
urlpatterns = [
    path('',views.home,name='home'),
    path('admin/', admin.site.urls),
    path('signup/',views.signupuser,name='signup'),
    path('clients/',views.clients,name='clients'),
    path('logout/',views.logoutuser,name='logoutuser'),
    path('login/',views.loginuser,name='login'),
    path('add-client/',views.add_client,name="add-client"),
    path('inventory/',views.inventory,name="inventory"),
    path('add_invoice/', views.add_invoice, name='add_invoice'),
    path('to-pdf', views.render_pdf_view, name='to_pdf'),
    
]

Invoice/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Client(models.Model):
    name = models.CharField(max_length=250)
    address_line1 = models.TextField(null=True,blank=True)
    state=models.CharField(max_length=250,null=True,blank=True)
    postal_code = models.CharField(max_length=100,null=True,blank=True)
    contact = models.CharField(max_length=50,null=True,blank=True)
    email_address = models.EmailField(null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)



    def __str__(self):
        return self.name


class Inventory(models.Model):
    UNITS = [
        ('ml','ml'),
        ('pcs','pcs'),
        ('ltr','ltr'),
        ('unit','unit'),
        ('kg','kg'),
        ('g','g'),
    ]
    name = models.CharField(max_length=250) 
    unit = models.CharField(max_length =10 ,choices=UNITS, blank=True,null=True)
    quantity = models.IntegerField(default=0)
    price = models.CharField(max_length=20)
    users= models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Invoice(models.Model):
	comments = models.TextField(max_length=3000, default='', blank=True, null=True)
	invoice_number = models.IntegerField(blank=True, null=True)
	invoice_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
	name = models.CharField('Customer Name', max_length=120, default='', blank=True, null=True)
	
	line_one = models.CharField('Line 1', max_length=120, default='', blank=True, null=True)
	line_one_quantity = models.IntegerField('Quantity', default=0, blank=True, null=True)
	line_one_unit_price = models.IntegerField('Unit Price (D)', default=0, blank=True, null=True)
	line_one_total_price = models.IntegerField('Line Total (D)', default=0, blank=True, null=True)

	line_two = models.CharField('Line 2', max_length=120, default='', blank=True, null=True)
	line_two_quantity = models.IntegerField('Quantity', default=0, blank=True, null=True)
	line_two_unit_price = models.IntegerField('Unit Price (D)', default=0, blank=True, null=True)
	line_two_total_price = models.IntegerField('Line Total (D)', default=0, blank=True, null=True)

	line_three = models.CharField('Line 3', max_length=120, default='', blank=True, null=True)
	line_three_quantity = models.IntegerField('Quantity', default=0, blank=True, null=True)
	line_three_unit_price = models.IntegerField('Unit Price (D)', default=0, blank=True, null=True)
	line_three_total_price = models.IntegerField('Line Total (D)', default=0, blank=True, null=True)

	line_four = models.CharField('Line 4', max_length=120, default='', blank=True, null=True)
	line_four_quantity = models.IntegerField('Quantity', default=0, blank=True, null=True)
	line_four_unit_price = models.IntegerField('Unit Price (D)', default=0, blank=True, null=True)
	line_four_total_price = models.IntegerField('Line Total (D)', default=0, blank=True, null=True)

	line_five = models.CharField('Line 5', max_length=120, default='', blank=True, null=True)
	line_five_quantity = models.IntegerField('Quantity', default=0, blank=True, null=True)
	line_five_unit_price = models.IntegerField('Unit Price (D)', default=0, blank=True, null=True)
	line_five_total_price = models.IntegerField('Line Total (D)', default=0, blank=True, null=True)

	phone_number = models.CharField(max_length=120, default='', blank=True, null=True)
	total = models.IntegerField(default='0', blank=True, null=True)
	balance = models.IntegerField(default='0', blank=True, null=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	last_updated = models.DateTimeField(auto_now_add=False, auto_now=True, blank=True)
	paid = models.BooleanField(default=False)
	invoice_type_choice = (
			('Receipt', 'Receipt'),
			('Proforma Invoice', 'Proforma Invoice'),
			('Invoice', 'Invoice'),
		)
	invoice_type = models.CharField(max_length=50, default='', blank=True, null=True, choices=invoice_type_choice)

	def __unicode__(self):
		return self.invoice_number
  
    

Invoice/forms.py
from dataclasses import field
from django.forms import ModelForm
from .models import Client,Invoice


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ['name','address_line1','state','contact','postal_code','email_address']



class InvoiceForm(ModelForm):
	class Meta:
		model = Invoice
		fields = ['name', 'phone_number', 'invoice_date',
				'line_one', 'line_one_quantity', 'line_one_unit_price', 'line_one_total_price','total', 'paid', 'invoice_type',
                'line_two','line_two_quantity','line_two_unit_price','line_two_total_price',
                'line_three','line_three_quantity','line_three_unit_price','line_three_total_price',
                'line_four','line_four_quantity','line_four_unit_price','line_four_total_price',
                'line_five','line_five_quantity','line_five_unit_price','line_five_total_price',
				]

Invoice/views.py
from django.db import IntegrityError
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from requests import request
from .forms import ClientForm,InvoiceForm
from .models import Client,Inventory
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
# Create your views here.


def home(request):
    return render(request,'Invoice/home.html')


def add_client(request):
    if request.method=='GET':
        return render(request,'Invoice/form.html',{'form':ClientForm()})
    else:
        form = ClientForm(request.POST)
        new_client = form.save(commit=False)
        new_client.user = request.user
        new_client.save()
        return redirect('clients')

def clients(request):
    clients = Client.objects.filter(user=request.user)
    return render(request,'Invoice/clients.html',{'clients':clients})

def inventory(request):
    items = Inventory.objects.filter(users=request.user)
    return render(request,'Invoice/inventory.html',{'items':items})

def signupuser(request):
    if request.method =='GET':
         return render(request,'Invoice/signup.html',{'form':UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('clients')
            except IntegrityError:
                return render(request,'Invoice/signup.html',{'form':UserCreationForm(),'error':'That username has already been taken'})
        else:
            return render(request,'Invoice/signup.html',{'form':UserCreationForm(),'error':'The passwords did not match'})



def loginuser(request):
    if request.method =='GET':
         return render(request,'Invoice/login.html',{'form':AuthenticationForm()})

    else:
        user = authenticate(request,username=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request,'Invoice/login.html',{'form':AuthenticationForm(),'error':'Wrong credentials'})
        else:
            login(request,user)
            return redirect('clients')


def logoutuser(request):
    if request.method=='POST':
        logout(request)
        return redirect('home')



def add_invoice(request):
   
    form = InvoiceForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        "form": form,
        "title": "New Invoice",
    }
    
    return render(request, "Invoice/invoice.html", context)


def render_pdf_view(request):
    template_path = 'Invoice/pdf.html'
    context = {'name': request.POST['name'],
    'date':request.POST['invoice_date'],
    'phone':request.POST['phone_number'],
    'line_one':request.POST['line_one'],
    'line_one_quantity':request.POST['line_one_quantity'],
    'line_one_price':request.POST['line_one_unit_price'],
    'line_one_total':request.POST['line_one_total_price'],
    
    'line_two':request.POST['line_two'],
    'line_two_quantity':request.POST['line_two_quantity'],
    'line_two_price':request.POST['line_one_unit_price'],
    'line_two_total':request.POST['line_two_total_price'],
    
    'line_three':request.POST['line_three'],
    'line_three_quantity':request.POST['line_three_quantity'],
    'line_three_price':request.POST['line_one_unit_price'],
    'line_three_total':request.POST['line_three_total_price'],
    
    'line_four':request.POST['line_four'],
    'line_four_quantity':request.POST['line_four_quantity'],
    'line_four_price':request.POST['line_one_unit_price'],
    'line_four_total':request.POST['line_four_total_price'],
    
    'line_five':request.POST['line_five'],
    'line_five_quantity':request.POST['line_five_quantity'],
    'line_five_price':request.POST['line_one_unit_price'],
    'line_five_total':request.POST['line_five_total_price'],
    
    'type':request.POST['invoice_type'],
    'total':request.POST['total']}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

    

Invoice/templates/invoice/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load crispy_forms_tags %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quick-Tab</title>
    

    <!--Bootstrap CDN Link -->
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">


    <!-- Google Fonts ----->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
</head>

{% if user.is_authenticated %}

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Quick-Tab</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link mx-5" aria-current="page" href="{% url 'clients' %}">Clients</a>
        </li>
        <li class="nav-item mx-5">
          <a class="nav-link" href="{% url 'inventory' %}">Inventory</a>
        </li>
       
        <li class="nav-item mx-5">
          <a class="nav-link" href="{% url 'add_invoice' %}">Invoices</a>
        </li>
      </ul>
      <form class="d-flex" role="search" method="POST" action="{% url 'logoutuser' %}">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">Logout</button>
      </form>
    </div>
  </div>
</nav>


{% block content %}


{% endblock %}

{% else %}

<head>
  <link rel="stylesheet" href="{% static 'Invoice/base.css' %}">
</head>
<body>
<section class="header">
    <nav class="navbar navbar-expand-lg  fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Quick-Tab</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item  px-3">
                <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link px-3" href="{% url 'signup' %}">Signup</a>
              </li>
             
            </ul>
          </div>
        </div>
      </nav>
      
      <div class="banner container">
          <div class="row">
              <div class="col-md-6">
                     
                  <h1>Stress less and manage your business with Quick-Tab, Your go-to billing system.</h1><br>
                  <a href="{% url 'login' %}" class="btn btn-dark banner-btns">Login</a>
                  <a href="{% url 'signup' %}" class="btn btn-secondary banner-btns">Signup</a>
              </div>
              <div class="col-md-6"><img src="{% static 'Invoice/banner-img.png' %}" alt="" class="img-fluid banner-img"></div>
          </div>
      </div>
</section>
<section class="about">
   
</section>
    



      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>



<!-- <a href="{% url 'login' %}">Login</a>
<a href="{% url 'signup' %}">Signup</a> -->

{% endif %}

</html>

Invoice/templates/invoice/clients.html
{% extends 'invoice/base.html' %}


{% block content %}

<section class="container">

    <h1 class="text-center mt-5">Your Clients</h1>

    <table class="table table-striped table-hover mt-5 ">
        <thead>
          <tr>
            
            <th scope="col">Name</th>
            <th scope="col">Contact</th>
            <th scope="col">Email</th>
          </tr>
        </thead>
        <tbody>

            {% for client in clients%}
          <tr>
           
            <th scope="row">{{client.name}}</th>
            <td>{{client.contact}}</td>
            <td>{{ client.email_address}}</td>
          </tr>
          
          {% endfor %}
        </tbody>
      </table>
</section>


{% endblock %}

Invoice/templates/invoice/form.html
{% extends 'Invoice/base.html' %}

{% block content %}
<h1>Form</h1>

<form method="POST">
{% csrf_token %}

    {{ form.as_p}}

    <button type="submit">Add</button>
</form>
{% endblock %}

Invoice/templates/invoice/home.html
{% extends 'invoice/base.html' %}


{% block content %}
<h1>Home</h1>

{% endblock %}

Invoice/templates/invoice/inventory.html
{% extends 'Invoice/base.html' %}

{% block content %}

<section class="container">

    <h1 class="text-center mt-5">Items in stock</h1>

    <table class="table table-striped table-hover mt-5 ">
        <thead>
          <tr>
            
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>

            {% for item in items %}
          <tr>
           
            <th scope="row">{{item.name}}</th>
            <td>{{item.quantity}}</td>
            <td>{{ item.unit}}</td>
            <td>{{ item.price}}</td>
          </tr>
          
          {% endfor %}
        </tbody>
      </table>
</section>


{% endblock %}

Invoice/templates/invoice/invoice.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">

<div class="text-center mt-5">
    <h2>Invoice</h2>
    <form method='POST' action="{% url 'to_pdf' %}" class="form-control">{% csrf_token %}
        <div class="row">
            <div class='col-sm-6'>
                <div class="row">
                  <div class="form-group col-md-6">
                    <label class="mt-3">Invoice Date</label> <br>
                    {{ form.invoice_date }} <br>
                    <label class="mt-3">Name</label> <br>
                    {{ form.name }} <br>
                  </div>
                  <div class="form-group col-md-6">
                    <label for="" class="mt-3">Phone Number</label> <br>
                    {{ form.phone_number }} <br>
                  </div>
                </div>
                <br>
                
                <div class="row">
                  <div class=" col-md-6 ">
                    <label for="">Items</label>
                   <br>
                    <span >{{ form.line_one }}</span>
                  </div>
                  <div class=" col-md-2">
                    <label for="">Quantity</label> <br>
                  <span class="">{{ form.line_one_quantity }}</span>  
                  </div>
                  <div class=" col-md-2">
                    <label for="">Price</label> <br>
                  <span class="">{{ form.line_one_unit_price }}</span>  
                  </div>
                  <div class=" col-md-2">
                    <label for="">Line Total</label>
                   <span class="">{{ form.line_one_total_price }}</span> 
                  </div>
                </div>

                <div class="row">
                    <div class=" col-md-6 ">
                     
                      <span id="l1">{{ form.line_two }}</span>
                    </div>
                    <div class=" col-md-2">
                      
                    <span class="">{{ form.line_two_quantity }}</span>  
                    </div>
                    <div class=" col-md-2">
                      
                    <span class="">{{ form.line_two_unit_price }}</span>  
                    </div>
                    <div class=" col-md-2">
              
                     <span class="">{{ form.line_two_total_price }}</span> 
                    </div>
                  </div>

                  <div class="row">
                    <div class=" col-md-6 ">
                     
                      <span id="l1">{{ form.line_three }}</span>
                    </div>
                    <div class=" col-md-2">
               
                    <span class="">{{ form.line_three_quantity }}</span>  
                    </div>
                    <div class=" col-md-2">
             
                    <span class="">{{ form.line_three_unit_price }}</span>  
                    </div>
                    <div class=" col-md-2">
         
                     <span class="">{{ form.line_three_total_price }}</span> 
                    </div>
                  </div>
                  <div class="row">
                    <div class=" col-md-6 ">
         
                      <span id="l1">{{ form.line_four }}</span>
                    </div>
                    <div class=" col-md-2">
             
                    <span class="">{{ form.line_four_quantity }}</span>  
                    </div>
                    <div class=" col-md-2">
                  
                    <span class="">{{ form.line_four_unit_price }}</span>  
                    </div>
                    <div class=" col-md-2">
           
                     <span class="">{{ form.line_four_total_price }}</span> 
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class=" col-md-6 ">
            
                      <span id="l1">{{ form.line_five }}</span>
                    </div>
                    <div class=" col-md-2">
             
                    <span class="">{{ form.line_five_quantity }}</span>  
                    </div>
                    <div class=" col-md-2">
               
                    <span class="">{{ form.line_five_unit_price }}</span>  
                    </div>
                    <div class=" col-md-2">
                   
                     <span class="">{{ form.line_five_total_price }}</span> 
                    </div>
                  </div>

                  <div class="row mt-5">
                    <div class="form-group col-md-12">
                      {{ form.invoice_type }}
                    </div>
                    <div class="form-group col-md-12 mt-3">
                        <label for="">Total</label>
                      {{ form.total }}
                    </div>
                  </div>
              

                <button type="submit" class="btn btn-primary mt-3">Generate</button>

                <!-- <input type="submit" value='Submit'/>   -->
            </div>
        </div>
    </form>
</div><!-- End myform -->

<script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script>
    $('#id_line_one_quantity, #id_line_one_unit_price, #id_line_two_quantity, #id_line_two_unit_price, #id_line_three_quantity, #id_line_three_unit_price, #id_line_four_quantity, #id_line_four_unit_price, #id_line_five_quantity, #id_line_five_unit_price, #id_line_six_quantity, #id_line_six_unit_price, #id_line_seven_quantity, #id_line_seven_unit_price, #id_line_eight_quantity, #id_line_eight_unit_price #id_line_nine_quantity, #id_line_nine_unit_price, #id_line_ten_quantity, #id_line_ten_unit_price').keyup(function(){
    var line_one_quantity_text = $('#id_line_one_quantity').val();
    var line_one_unit_price_text = $('#id_line_one_unit_price').val();
    var line_one_total = line_one_quantity_text * line_one_unit_price_text

    var line_two_quantity_text = $('#id_line_two_quantity').val();
    var line_two_unit_price_text = $('#id_line_two_unit_price').val();
    var line_two_total = line_two_quantity_text * line_two_unit_price_text

    var line_three_quantity_text = $('#id_line_three_quantity').val();
    var line_three_unit_price_text = $('#id_line_three_unit_price').val();
    var line_three_total = line_three_quantity_text * line_three_unit_price_text
    
    var line_four_quantity_text = $('#id_line_four_quantity').val();
    var line_four_unit_price_text = $('#id_line_four_unit_price').val();
    var line_four_total = line_four_quantity_text * line_four_unit_price_text

    var line_five_quantity_text = $('#id_line_five_quantity').val();
    var line_five_unit_price_text = $('#id_line_five_unit_price').val();
    var line_five_total = line_five_quantity_text * line_five_unit_price_text

    var line_six_quantity_text = $('#id_line_six_quantity').val();
    var line_six_unit_price_text = $('#id_line_six_unit_price').val();
    var line_six_total = line_six_quantity_text * line_six_unit_price_text

    var line_seven_quantity_text = $('#id_line_seven_quantity').val();
    var line_seven_unit_price_text = $('#id_line_seven_unit_price').val();
    var line_seven_total = line_seven_quantity_text * line_seven_unit_price_text

    var line_eight_quantity_text = $('#id_line_eight_quantity').val();
    var line_eight_unit_price_text = $('#id_line_eight_unit_price').val();
    var line_eight_total = line_eight_quantity_text * line_eight_unit_price_text

    var line_nine_quantity_text = $('#id_line_nine_quantity').val();
    var line_nine_unit_price_text = $('#id_line_nine_unit_price').val();
    var line_nine_total = line_nine_quantity_text * line_nine_unit_price_text

    var line_ten_quantity_text = $('#id_line_ten_quantity').val();
    var line_ten_unit_price_text = $('#id_line_ten_unit_price').val();
    var line_ten_total = line_ten_quantity_text * line_ten_unit_price_text

    var total = line_one_total + line_two_total + line_three_total + line_four_total + line_five_total;

    $('#id_line_one_total_price').val(line_one_total);
    $('#id_line_two_total_price').val(line_two_total);
    $('#id_line_three_total_price').val(line_three_total);
    $('#id_line_four_total_price').val(line_four_total);
    $('#id_line_five_total_price').val(line_five_total);

    $('#id_total').val(total);
});
</script>

Invoice/templates/invoice/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <!--------------Bootstrap CDN Link ------------------->
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'Invoice/login.css' %}">
</head>
<body>
    <section class="container text-center form">
        <h1 class="heading">Login</h1>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{form.as_p}}
        
            <button type="submit" class="btn btn-dark">Login</button>
        </form>
        
        
        
        <h6 class="text-danger mt-5">{{error}}</h6>
    </section>
    
    



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

Invoice/templates/invoice/pdf.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">


<div class=" mt-5">
    <h1>{{type}}</h1>

   <b>Name :</b>  {{name}} <br>
   <b>Phone No :</b>  {{phone}} <br>
   <b>Date :</b>  {{date}} <br>

    <hr>

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Line Total</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th class="text-center px-5 ms-auto" scope="row">1</th>
            <td class="text-center px-5 ms-auto">{{line_one}}</td>
            <td class="text-center px-5 ms-auto">{{line_one_quantity}}</td>
            <td class="text-center px-5 ms-auto">{{line_one_price}}</td>
            <td class="text-center px-5 ms-auto">{{line_one_total}}</td>
          </tr>
          

          {% if line_two %}
          <tr>
            <th scope="row">1</th>
            <td class="text-center px-5 ms-auto">{{line_two}}</td>
            <td class="text-center px-5 ms-auto">{{line_two_quantity}}</td>
            <td class="text-center px-5 ms-auto">{{line_two_price}}</td>
            <td class="text-center px-5 ms-auto">{{line_two_total}}</td>
          </tr>
{% endif %}

{% if line_three %}
          <tr>
            <th scope="row">1</th>
            <td class="text-center px-5 ms-auto">{{line_three}}</td>
            <td class="text-center px-5 ms-auto">{{line_three_quantity}}</td>
            <td class="text-center px-5 ms-auto">{{line_three_price}}</td>
            <td class="text-center px-5 ms-auto">{{line_three_total}}</td>
          </tr>
          {% endif %}
          {% if line_four %}
          <tr>
            <th scope="row">1</th>
            <td class="text-center px-5 ms-auto">{{line_four}}</td>
            <td class="text-center px-5 ms-auto">{{line_four_quantity}}</td>
            <td class="text-center px-5 ms-auto">{{line_four_price}}</td>
            <td class="text-center px-5 ms-auto">{{line_four_total}}</td>
          </tr>
          {% endif %}
          {% if line_five %}

          <tr>
            <th scope="row">1</th>
            <td class="text-center px-5 ms-auto">{{line_five}}</td>
            <td class="text-center px-5 ms-auto">{{line_five_quantity}}</td>
            <td class="text-center px-5 ms-auto">{{line_five_price}}</td>
            <td class="text-center px-5 ms-auto">{{line_five_total}}</td>
          </tr>
          {% endif %}
        </tbody>
      </table>

<br><br><br><br>
      <h4>Total Amount : Rs. {{total}}</h4>

</div>



<script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

Invoice/templates/invoice/signup.html
<h1>Signup</h1>


<form method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">Sign Up</button>
</form>

<h2>{{error}}</h2>